# Číslo prvního vlaku, který odjíždí ze stanice Heřmánky, a doba tohoto odjezdu.
# An EVN of a train which departs from the Heřmánky station as first, and when.

PREFIX ex: <http://example.org/vocabulary/>
PREFIX gtfs: <http://vocab.gtfs.org/terms>
PREFIX pext: <http://www.ontotext.com/proton/protonext> 
PREFIX dbpedia-owl: <https://dbpedia.org/ontology/>

Select ?evn ?dtime
where 
{
?train a dbpedia-owl:Train ;
 ex:europeanVehicleNumber ?evn .

?train ex:rides ?conn .
?conn ex:connects ?stop .
?stop ex:departureTime ?dtime.

?station ex:serves ?stop .
?station ex:stationName "Heřmánky"@cs .

}

order by ?dtime
