# SPZ autobusů, které vyrobila TATRA TRUCKS a.s.
# License plates of buses manufactured by TATRA TRUCKS a.s., and their purchasing prices

PREFIX ex: <http://example.org/vocabulary/>
Select ?spz ?price
where 
{
?bus a ex:Bus ;
  ex:licensePlateNumber ?spz ;
  ex:purchasePrice ?price .

?producer ex:produces ?bus ;
  ex:legalName ?name .
  
FILTER(?name = "TATRA TRUCKS a.s."@cs)
}
ORDER BY ?price